source "https://supermarket.chef.io"

cookbook "visualstudio"
cookbook "resharper"
cookbook "chrome"
cookbook "notepadpp"
cookbook "seven_zip"
cookbook "git"
cookbook "beyondcompare"
cookbook "fiddler"
cookbook "chocolatey-installer"
cookbook "sql_server"